@baseUrl = http://localhost:4040/api/v1
@userName = exampleUser
@email = exampleUser@example.com
@password = exampleUser

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmUzZTBmY2UzYTE4MDY5MzZhZmRjYjYiLCJpYXQiOjE3MjYyMTE3NTZ9.y7boe5EtRPlmiBxPFe2TbOiwYgJoheanxVLhOsd2P1s

### Register a new user (expected to fail)
POST {{baseUrl}}/accounts/register
Content-Type: application/json

{
  "userName": "john_doe",
  "fullName": "John Doe",
  "email": "john.doe@example.com",
  "password": "securePassword123"
}

### Login with the registered user
POST {{baseUrl}}/accounts/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}



### Login with incorrect credentials (expected to fail)
POST {{baseUrl}}/accounts/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "wrongPassword"
}

### Add an income
POST {{baseUrl}}/incomes
Content-Type: application/json

{
    "name":"myexpenses",    # Required
    "amount":150000,        # Required
    "currencyType":"LKR",   # 
    "monthly":true,
    "monthlyDate":5,
    "paid": 
}