FROM node:latest
# get build time properties
# ARG FMEXPRESSPORT=4040
# ARG FMJWTSYMETRICKEY="dfjalksfjkasfjkfjaksjflaksjflkasjfkasjfklasjfaksjflkasjfksfjkasf"
# ARG FMDBCONNECTIONSTRING="localhost/financeManagement"
ARG FMEXPRESSPORT
ARG FMJWTSYMETRICKEY
ARG FMDBCONNECTIONSTRING
RUN if [ -z "$FMEXPRESSPORT" ] || [ -z "$FMJWTSYMETRICKEY" ] || [ -z "$FMDBCONNECTIONSTRING" ]; then \
        echo "Error: Required build arguments are missing." && exit 1; \
    fi
# RUN ["mkdir","-p","/home/application/node_modules"]
ENV FMEXPRESSPORT=${FMEXPRESSPORT}
ENV FMJWTSYMETRICKEY=${FMJWTSYMETRICKEY}
ENV FMDBCONNECTIONSTRING=${FMDBCONNECTIONSTRING}
EXPOSE 4040
EXPOSE 4050
COPY . /home/application
WORKDIR /home/application
RUN ["npm","i"]
ENTRYPOINT [ "npm", "run","start" ]
# ENTRYPOINT [ "node", "index.js" ]


# docker build --build-arg FMEXPRESSPORT=${FMEXPRESSPORT} --build-arg FMJWTSYMETRICKEY=${FMJWTSYMETRICKEY} --build-arg FMDBCONNECTIONSTRING=${FMDBCONNECTIONSTRING} -t backend .