on:
  push:
    branches:
      - master
      - test

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{secrets.DOCKERHUB_REPOSITORY}}:latest
          build-args: |
            FMEXPRESSPORT=${{ secrets.FMEXPRESSPORT }} 
            FMJWTSYMETRICKEY=${{ secrets.FMJWTSYMETRICKEY }} 
            FMDBCONNECTIONSTRING=${{ secrets.FMDBCONNECTIONSTRING }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build_and_push
  #   steps:
  #     - name: Execute remote commands over ssh in server 1
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{secrets.SSH_HOST1}}
  #         username: ${{secrets.SSH_USERNAME}}
  #         password: ${{secrets.SSH_PASSWORD}}
  #         script: |
  #           # change the directory
  #           cd /home/lahirukasunidilhara

  #           # down the docker compose if previous compose is up
  #           docker compose down

  #           # run the docker-compose file
  #           docker compose up -d

  #     - name: Execute remote commands over ssh in server 2
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{secrets.SSH_HOST2}}
  #         username: ${{secrets.SSH_USERNAME}}
  #         password: ${{secrets.SSH_PASSWORD}}
  #         script: |
  #           # change the directory
  #           cd /home/lahirukasunidilhara

  #           # down the docker compose if previous compose is up
  #           docker compose down

  #           # run the docker-compose file
  #           docker compose up -d
